#+html: <a name="28"></a>
** J28: Manual vs. Automatic Memory Management :G4:Lab:

 #+begin_summary
Explain the difference between manual memory management (as
exemplified by C) and automatic memory management (as exemplified
by Java). Explain the life cycle of objects (allocations). Also,
for a suitable Java program, explain when memory is actually
deallocated (as opposed to being unreachable).
#+end_summary

 Redovisa bland annat för:

 - När är ett objekt att betrakta som skräp som kan städas bort?
 - När städas skräp bort?
 - Hur kan jag som programmerare ta reda på när ett visst objekt städats bort?
 - Finns det någon typ av minnesfel som jag kan få i C med pekare som jag inte kan få med referenser i Java?
 - När allokeras minne och hur tar Java reda på hur många bytes ett visst objekt kräver?
 - Hur tar jag som programmerare reda på hur många bytes ett visst objekt kräver?

 Javas automatiska skräpsamlare kan konfigureras på många sätt, så tänk dig för varenda gång du säger "så här fungerar Javas GC".

 Bonus: hur fungerar "weak references"? Hur relaterar de till pekare?



-----

*Report a bug on this achievement?* Please place an issue on [[https://github.com/IOOPM-UU/achievements/issues/new?title=Bug%20in%20achievement%20J28&body=Please%20describe%20the%20bug,%20comment%20or%20issue%20here&assignee=TobiasWrigstad][GitHub]].
