#+html: <a name="43"></a>
** O43: Profilering och optimering 2/3 :G4:Lab: 

 #+BEGIN_SUMMARY
 Med ledning resultatet från föregående mål, optimera programmet på ett förtjänstfullt sätt.
 #+END_SUMMARY

 Observera att dessa mål passar särskilt bra under projektet.

 Optimera programmet med hjälp av profilen ovan, motivera ansatsen
 och demonstrera och förklara prestanda-*ökningen* med hjälp av en
 ny profil för det optimerade programmet

 I nödfall kan man bli godkänd på detta mål trots att man inte kan
 jaga fram en prestandaökning om den optimering man gjort (som
 visat sig vara en "falsk optimering") intuitivt verkar vara en
 optimering.

 Observera att det är dumt att optimera ett grafiskt program typ
 lagerhanteraren. Däremot kan man optimera /delar/ av
 lagerhanteraren. Ta binärträdsbalanseringen som ett exempel. Den
 går kanske att göra bättre utan att först skriva ned hela trädet i
 en array?

 Sedan får man demonstrera uppdateringen kanske genom att göra *1
 miljon* insättning av varor i databasen och göra 1 miljon
 sökningar med de olika sorteringsimplementationerna och jämföra.



-----

*Report a bug on this achievement?* Please place an issue on [[https://github.com/IOOPM-UU/achievements/issues/new?title=Bug%20in%20achievement%20O43&body=Please%20describe%20the%20bug,%20comment%20or%20issue%20here&assignee=TobiasWrigstad][GitHub]].
