#+html: <a name="43"></a>
** O43: Profilering och optimering 2/3 :G4:Lab: 

 #+BEGIN_SUMMARY
 Med ledning resultatet från föregående mål, optimera programmet på ett förtjänstfullt sätt.
 #+END_SUMMARY

 Observera att dessa mål passar särskilt bra under projektet.

 Optimera programmet med hjälp av profilen ovan, motivera ansatsen
 och demonstrera och förklara prestanda-*ökningen* med hjälp av en
 ny profil för det optimerade programmet

 I nödfall kan man bli godkänd på detta mål trots att man inte kan
 jaga fram en prestandaökning om den optimering man gjort (som
 visat sig vara en "falsk optimering") intuitivt verkar vara en
 optimering.

 Observera att det är dumt att optimera ett interaktivt program
 som t.ex. Assigment 2. Däremot kan man optimera /delar/ av dess
 underliggande modell. Ta hashtabellen som ett exempel.
 Implementation av dynamisk storleksförändring ("Adapting the
 Number of Buckets") är ett utmärkt exempel på en optimering som
 förändrar tiden för insättning och borttagning.

 Sedan får man demonstrera uppdateringen kanske genom att göra $N$
 insättningar av element och göra $M$ sökningar med de olika
 sorteringsimplementationerna och jämföra (för /stora/ värden på
 $N$ och $M$ för att se skillnad -- millisekunder är inte stora
 nog).



-----

*Report a bug on this achievement?* Please place an issue on [[https://github.com/IOOPM-UU/achievements/issues/new?title=Bug%20in%20achievement%20O43&body=Please%20describe%20the%20bug,%20comment%20or%20issue%20here&assignee=TobiasWrigstad][GitHub]].
