#+html: <a name="55"></a>
** TODO T55: Mer Avacerad Versionhantering                           :G3:Lab:

Detta mål är nytt för 2020. Det står på vår lista att förbättra denna text. 

När man utvecklar kod har man ofta flera version av samma program
igång som kanske utvecklas parallellt av olika personer,
alternativt man experimenterar med någon utökning eller förändring
för att se konsekvensen för programmet i stort. Detta gör att en
kodbas förgrenar sig, vilket i regel finns stöd för i moderna
versionshanteringssystem.

- Lär dig att arbeta med branches som är förgreningar i koden. 
- Lär dig att bemästra ett arbetsflöde där du skapar en ny branch för en specifik ny feature, visa att du kan göra rebase på din branch för att synka med förändringar i "master branch", och integrera den med master.
- Lär dig att skapa pull requests från branches och integrera dem i master branch.
- Lär dig att frisera din commit-historik så att versionsloggen blir tydlig och lätt att följa. 

Demonstration av detta mål skall -- som vanligt -- ske på kod i inluppar eller projekt. Det viktiga här är att förstå koncepten, terminologin och det bakomliggande syftet. 

-----

*Report a bug on this achievement?* Please place an issue on [[https://github.com/IOOPM-UU/achievements/issues/new?title=Bug%20in%20achievement%20T55&body=Please%20describe%20the%20bug,%20comment%20or%20issue%20here&assignee=TobiasWrigstad][GitHub]].
