#+html: <a name="61"></a>
** TODO X61: Running Group Meetings Responsibly          :G3:Special:New2019:

#+BEGIN_SUMMARY
Participate in five group meetings throughout the course and hand
in the corresponding reports.
#+END_SUMMARY

The group meetings serve as a way for students to come up for air,
talk about what's hard, what's possible, exchange useful advice
etc. The course website includes useful information about group
meetings on the [[file:team.org][Team]] page. 

To tick off this goal, you must participate in all the meetings
for your group. Follow the instructions for running meetings and
hand in the report, which should contain the names of everyone
present at the meeting. Email the report to
[[mailto:ioopm@it.uu.se][ioopm@it.uu.se]] and
CC your coach who takes care of checking who is present and
eventually ticking this goal off for you. 

*You must keep track of what meetings you have or have not
attended.* If you fail to show up for a meeting, take this up with
the coach first, who will likely refer you to the head teacher who
will give you an extra assignment instead.

-----

*Report a bug on this achievement?* Please place an issue on [[https://github.com/IOOPM-UU/achievements/issues/new?title=Bug%20in%20achievement%20X61&body=Please%20describe%20the%20bug,%20comment%20or%20issue%20here&assignee=TobiasWrigstad][GitHub]].
