#+html: <a name="64"></a>
** Y64: Använd en namngiven utvecklingsprocess och reflektera över utkomsten :G3:Report:

 Redovisning sker genom en gemensam (för alla medlemmar i
 projektet) skriftlig beskrivning av den valda processen (på hög
 nivå) samt en reflektion över dess styrkor och svagheter i
 projektrapporten. Om ni skulle starta om projektet imorgon -- vad
 skulle ni behålla och vad skulle ni göra annorlunda (och hur)?

 Visa också upp projektets burndown chart för samtliga sprintar.

 Några frågor att starta med:

 - Vilken process valdes? Varför? 
 - Hur följdes processen? 
 - Hur fungerade processen?
 - Var antalet sprintar lämpligt?
 - Var längden på sprintarna bra?
 - Var planeringen optimistisk/pessimistisk/bra?
 - Låg planeringen på en lagom detaljnivå?
 - Kunde man se tendenser till att över- eller underskatta vissa tasks?
 - Tidsfördelning? 


-----

*Report a bug on this achievement?* Please place an issue on [[https://github.com/IOOPM-UU/achievements/issues/new?title=Bug%20in%20achievement%20Y64&body=Please%20describe%20the%20bug,%20comment%20or%20issue%20here&assignee=TobiasWrigstad][GitHub]].
