#+html: <a name="66"></a>
** Y66: Tillämpa kodgranskning löpande :G3:Report:

 Tidigare under kursen har ni tillämpad kodgranskning på helt nya
 program som inte skrivit. Under projektet får ni äntligen
 tillfälle att tillämpa kodgranskning på ett liknande sätt som
 används ute i verkligheten: istället för helt ny kod får ni ofta
 titta på kod som fixar något i existerande kod, eller bygger
 vidare på existerande kod som ni känner till.

 I projektet arbetar ni med branches eller forks från master. Ni
 kan ha branches i ert delade repo, eller personliga (privata)
 forks i era egna privata repon. Innan något commitas till master
 skall ni granska koden -- alltså någon som inte skrev koden skall
 läsa igenom den och trycka på mergeknappen.

 Ute i arbetslivet gör man detta av flera anledningar:

 - Kvalitetssäkring
 - Utvecklare blir modigare när man delar ansvar för korrekthet
 - När man vet att någon måste läsa koden skriver man ofta bättre kod
 - Man sprider kunskap om vad som händer i projektet till fler

 Redovisa i projektrapporten hur denna typ av kodgranskining har
 fungerat och relatera till den typ som gjordes under tidigare
 faser, som var mindre disciplinerad och inte rörde er egen kod.

 Om ni skulle starta om projektet imorgon -- vad skulle ni behålla
 och vad skulle ni göra annorlunda (och hur)?

 Det är frivilligt att använda [[https://github.com/IOOPM-UU/ioopm15/blob/master/extramaterial/kodgranskningsprotokoll.pdf][kodgranskningsprotokoll]] här.


-----

*Report a bug on this achievement?* Please place an issue on [[https://github.com/IOOPM-UU/achievements/issues/new?title=Bug%20in%20achievement%20Y66&body=Please%20describe%20the%20bug,%20comment%20or%20issue%20here&assignee=TobiasWrigstad][GitHub]].
